version: '3.8'

services:
  dev-machine:
    image: ://microsoft.com
    volumes:
      # 깃허브 Codespaces의 표준 기본 경로로 매핑합니다.
      - ..:/workspaces:cached

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    network_mode: "service:dev-machine"

volumes:
  n8n_data:
